import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import SideNavbar from "@/components/SideNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard for companies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen bg-neutral-950 w-full flex text-white",inter.className,{"debug-screens" : process.env.NODE_ENV === "development"})}>
        {/* Sidebar */}
        <SideNavbar/>
        <main className="p-8 w-full">
          {children}
          </main>
        </body>
    </html>
  );
}
